spring:
  application:
    name: test-task
  datasource:
    url: jdbc:postgresql://localhost:5432/testtask    # jdbc:h2:mem:testtask
    username: postgres    # sa
    password: dv9899     # password
    driver-class-name: org.postgresql.Driver      # org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform=: org.hibernate.dialect.PostgreSQLDialect  # org.hibernate.dialect.H2Dialect
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      platform: postgres

